
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Profiling Configuration parameters. These parameters
* can be overwritten through run configuration in SDK
*
*******************************************************************/

#ifndef _PROFILE_CONFIG_H
#define _PROFILE_CONFIG_H

#define BINSIZE 4
#define CPU_FREQ_HZ 650000000
#define SAMPLE_FREQ_HZ 100000
#define TIMER_CLK_TICKS 6500
#define PROC_CORTEXA9 1
#define ENABLE_SCU_TIMER 1
#define ENABLE_SYS_INTR 1
#define PROFILE_TIMER_BASEADDR 0xF8F00600
#define PROFILE_TIMER_INTR_ID 29
#define SCUGIC_CPU_BASEADDR 0xF8F00100
#define SCUGIC_DIST_BASEADDR 0xF8F01000

#endif

/******************************************************************/

