# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z1.xdc

# Block Designs: bd/mpsoc_only_ps_gpio_design/mpsoc_only_ps_gpio_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_only_ps_gpio_design || ORIG_REF_NAME==mpsoc_only_ps_gpio_design} -quiet] -quiet

# IP: bd/mpsoc_only_ps_gpio_design/ip/mpsoc_only_ps_gpio_design_processing_system7_0_1/mpsoc_only_ps_gpio_design_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_only_ps_gpio_design_processing_system7_0_1 || ORIG_REF_NAME==mpsoc_only_ps_gpio_design_processing_system7_0_1} -quiet] -quiet

# XDC: /home/varun/coding/fpga/xylinx/pynq_z1/mpsoc_only_ps_gpio/mpsoc_only_ps_gpio.gen/sources_1/bd/mpsoc_only_ps_gpio_design/mpsoc_only_ps_gpio_design_ooc.xdc
